---
title: Contantes Entières
categories: [ "Variables" ]
subCategories: [ "Constantes" ]
---




= Contantes Entières


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Les constantes entières sont des nombres utilisés directement dans un 'sketch', comme 123. Par défaut, ces nombres sont traités comme des link:../../data-types/int[int] mais vous pouvez changer cela en utilisant les modificateurs 'U' et 'L' (voir ci-dessous).
[%hardbreaks]

Normalement, les constantes entières sont traitées comme des entiers de base 10 (décimaux), mais une notation spéciale (formateurs) peut être utilisée pour saisir des nombres dans d'autres bases.
[%hardbreaks]

|===
|Base |Exemple |Formateur |Commentaire

|10 (décimal)
|123
|aucun
|

|2 (binaire)
|B1111011
|entête 'B'
|ne fonctionne qu'avec des valeurs de 8 bits (de 0 à 255)   les caractères 0&1 sont valides

|8 (octal)
|0173
|entête "0"
|les caractères 0-7 sont valides

|16 (héxadecimal)
|0x7B
|entête "0x"
|les caractères 0-9, A-F, a-f sont valides
|===
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
== Décimal (base 10)
C'est la notation avec laquelle vous êtes familier. Les constantes sans autres préfixes sont considérées comme étant au format décimal.

[float]
=== Code d'exemple:
[source,arduino]
----
n = 101;     // pareil que 101 en décimal   ((1 * 10^2) + (0 * 10^1) + 1)
----
[%hardbreaks]

[float]
== Binaire (base 2)
Seuls les caractères 0 et 1 sont valides.

[float]
=== Code d'exemple:
[source,arduino]
----
n = B101;    // pareil que 5 en décimal   ((1 * 2^2) + (0 * 2^1) + 1)
----

Le formateur binaire ne fonctionne que sur des octets (8 bits) entre 0 (B0) et 255 (B11111111). S'il vous est pratique d'entrer un int (16 bits) sous forme binaire, vous pouvez le faire en deux étapes:
[source,arduino]
----
myInt = (B11001100 * 256) + B10101010;    // B11001100 est l'octet de poid fort`
----
[%hardbreaks]

[float]
== Octal (base 8)
Seuls les caractères de 0 à 7 sont valides. Les valeurs octales sont indiquées par le préfixe "0" (zéro).

[float]
=== Code d'exemple:
[source,arduino]
----
n = 0101;    // pareil que 65 en décimal   ((1 * 8^2) + (0 * 8^1) + 1)
----
Il est possible de générer un bogue difficile à trouver en insérant (involontairement) un zéro avant une constante ce qui aura pour conséquence de demander au compilateur d'interpréter (involontairement) votre constante comme octale.
[%hardbreaks]

[float]
== Héxadecimal (base 16)
Les caractères valides sont compris entre 0 et 9 et les lettres A à F; A a la valeur 10, B 11, jusqu'à F, qui est 15. 
Les valeurs hexadécimales sont indiquées par le préfixe "0x". Notez que A-F peut être défini en majuscules ou en minuscules (a-f).

[float]
=== Code d'exemple:
[source,arduino]
----
n = 0x101;   // pareil que 257 en décimal   ((1 * 16^2) + (0 * 16^1) + 1)
----
[%hardbreaks]


[float]
=== Notes et Avertissements
*Les formateurs U & L:*

Par défaut, une constante entière est traitée comme un entier avec les limitations inhérentes aux valeurs. Pour spécifier une constante entière avec un autre type de données, faites comme suit:

  - un 'u' ou 'U' pour forcer la constante dans un format de données non signé. Exemple: 33u
  - un 'l' ou 'L' pour forcer la constante dans un format de données long. Exemple: 100000L
  - un 'ul' ou 'UL' pour forcer la constante dans un format de données long non signé. Exemple: 32767ul

[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Voir également

[role="language"]

--
// SEE ALSO SECTION ENDS
